[workspace]

resolver = "2"

members = [
    "ads1220",
    "late-mate-cli", "late-mate-device",
    "late-mate-shared",
    "late-mate-validation"
]

[profile.dev]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "fat"
