build-load-cli:
    cd ../late-mate-cli && \
      RUST_LOG=debug cargo build --release --bin late-mate --target aarch64-unknown-linux-gnu && \
      scp ../target/aarch64-unknown-linux-gnu/release/late-mate dg@raspberrypi.local:

build-load-validationtool:
    cargo build --release --target aarch64-unknown-linux-gnu && \
      scp ../target/aarch64-unknown-linux-gnu/release/late-mate-validation dg@raspberrypi.local: