[package]
name = "late-mate-firmware"
version = "0.1.0"
edition = "2021"

[dependencies]
embassy-embedded-hal = { version = "0.1.0", features = ["defmt"] }
embassy-sync = { version = "0.5.0", features = ["defmt"] }
embassy-executor = { version = "0.5.0", features = ["task-arena-size-32768", "arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers"] }
embassy-time = { version = "0.3.0", features = ["defmt"] }
embassy-rp = { version = "0.1.0", features = ["defmt", "unstable-pac", "time-driver", "critical-section-impl"] }
embassy-usb = { version = "0.1.0", features = ["defmt"] }
embassy-futures = { version = "0.1.1" }

defmt = "0.3"
defmt-rtt = "0.4"

cortex-m = { version = "0.7.7" }
cortex-m-rt = "0.7.3"

panic-probe = { version = "0.3.1", features = ["print-defmt"] }

usbd-hid = "0.7"

numtoa = "0.2.4"

# required for static_cell to compile (it enables CAS emulation)
portable-atomic = { version = "1.6", features = ["critical-section"] }
static_cell = { version = "2", features = [] }
bitfield-struct = "0.6.0"
log = "0.4.20"

# shared stuff
ads1220 = { path = "../host_and_shared/ads1220" }
late-mate-comms = { path = "../host_and_shared/late-mate-comms" }
postcard = "1.0.8"

# see https://embassy.dev/book/dev/getting_started.html#_it_didnt_work
[profile.release]
debug = 2
